version: '3.7'
services:
  dapr-receiver:
    build: .
    image: dapr-receiver
    container_name: dapr-receiver
    environment:
      AZURE_SERVICE_BUS_HOST: ${AZURE_SERVICE_BUS_HOST}
      AZURE_SERVICE_BUS_USERNAME: ${AZURE_SERVICE_BUS_USERNAME}
      AZURE_SERVICE_BUS_PASSWORD: ${AZURE_SERVICE_BUS_PASSWORD}
      AZURE_SERVICE_BUS_QUEUE: ${AZURE_SERVICE_BUS_QUEUE}
      AZURE_SERVICE_BUS_TOPIC: ${AZURE_SERVICE_BUS_TOPIC}
      AZURE_SERVICE_BUS_SUBSCRIPTION: ${AZURE_SERVICE_BUS_SUBSCRIPTION}
