version: '3.7'
services:
  dapr-receiver:
    build:
      context: .
      target: development
    ports:
      - "9230:9229"
    volumes:
      - ./app/:/home/node/app/
      - ./package.json:/home/node/package.json
