version: '3.7'
services:
  dapr-receiver:
    build:
      context: .
      target: development
    ports:
      - "9230:9229"
    volumes:
      - ./app/:/home/node/app/
      - ./package.json:/home/node/package.json
    depends_on:
      - redis
      - placement

  dapr-sender-dapr:
    image: "daprio/daprd:edge"
    command: ["./daprd",
     "-app-id", "dapr-receiver",
     "-placement-host-address", "placement:50006",
     "-dapr-grpc-port", "50002",
     "-components-path", "/components"]
    volumes:
        - "./dapr/components/:/components"
    depends_on:
      - dapr-receiver
    network_mode: "service:dapr-receiver"

  redis:
    image: "redis:alpine"
    ports:
      - "6381:6379"

  placement:
    image: "daprio/dapr"
    command: ["./placement", "-port", "50006"]
    ports:
      - "50007:50006"
