version: '3.7'
services:
  dapr-receiver:
    build:
      context: .
      target: development
    environment:
      PORT: 3001
      AZURE_SERVICE_BUS_CONNECTION_STRING: ${AZURE_SERVICE_BUS_CONNECTION_STRING}
    ports:
      - "3001:3001"
      - "9230:9229"
    volumes:
      - ./app/:/home/node/app/
      - ./package.json:/home/node/package.json
    depends_on:
      - redis
      - placement

  dapr-sender-dapr:
    image: "daprio/daprd:edge"
    command: ["./daprd",
     "-app-id", "daprreceiver",
     "-app-port", "3001",
     "-components-path", "/components"]
    volumes:
        - "./dapr/components/:/components"
    depends_on:
      - dapr-receiver
    network_mode: "service:dapr-receiver"

  redis:
    image: "redis:alpine"
    ports:
      - "6381:6379"

  placement:
    image: "daprio/dapr"
    command: ["./placement", "-port", "50006"]
    ports:
      - "50007:50006"
